version: '3'

services:
  leaderboard.webapi:
    image: alexthissen/leaderboard.webapi
    build:
      context: ./src/Services/Leaderboard.WebAPI
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux

  gamingwebapp:
    image: alexthissen/gamingwebapp
    build:
      context: ./src/Applications/GamingWebApp
      dockerfile: Dockerfile
    depends_on:
      - leaderboard.webapi