version: '3'

services:
  leaderboard.webapi:
    image: techdays2017/leaderboard.webapi
    build:
      context: ./src/Services/Leaderboard.WebAPI
      dockerfile: Dockerfile

  gamingwebapp:
    image: techdays2017/gamingwebapp
    build:
      context: ./src/Applications/GamingWebApp
      dockerfile: Dockerfile
    depends_on:
      - leaderboard.webapi