version: '3'

services:
  leaderboardwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:1339
      - ConnectionStrings:LeaderboardContext=Server=tcp:killer-apps.database.windows.net,1433;Initial Catalog=LeaderboardNETCore;Persist Security Info=False;User ID=techdays2017;Password=abc123!@;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - "1339:1339"

  gamingwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LeaderboardWebApiBaseUrl=http://leaderboardwebapi:1339
    ports:
      - "8089:80"